# Generate this file (without this message) by running at the repo root
# nestle . --git-only

[[tests]]

[[tests.nestle]]

[[tests.nestle.root_directory]]

[[tests.nestle.root_directory.folder_a]]

[[tests.nestle.root_directory.folder_a.folder_b]]

[tests.nestle.root_directory.folder_a.folder_b.".env.example"]
content = "SECRET_KEY=secret key here"
[[tests.nestle.root_directory.python_package]]

[tests.nestle.root_directory.python_package."__init__.py"]
content = ""
[tests.nestle.root_directory.python_package."python_source_file.py"]
content = """
# useful python source code
def true_or_false(arg):
    if arg is True:
        return True
    else:
        return False
"""
[[tests.unnestle]]

[[tests.unnestle.files]]

[[tests.unnestle.files.personal-animated-gif-collection]]

[tests.unnestle.files.personal-animated-gif-collection."not_bad-small.gif"]
source = "./tests/unnestle/files/personal-animated-gif-collection/not_bad-small.gif"
[tests.unnestle.files."readme-template-version-2.md"]
content = """
# Your Project Name Here
The description... Remember to explain what your project does, and not just how cool you think it is!
"""
[tests.unnestle."example.nestle.toml"]
source = "./tests/unnestle/example.nestle.toml"
[[src]]

[[src.nestle_text]]

[src.nestle_text."__init__.py"]
content = ""
[src.nestle_text."nestle.py"]
source = "./src/nestle_text/nestle.py"
[src.nestle_text."unnestle.py"]
source = "./src/nestle_text/unnestle.py"

[LICENSE]
content = """
Copyright (c) 2023 Zagaran, Inc

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

[".gitignore"]
source = "./.gitignore"

["pyproject.toml"]
content = """
[project]
name = "nestle-text"
version = "0.0.1"
authors = [
  { name="John Wiltshire-Gordon", email="jwiltshiregordon@gmail.com" },
]
description = "A lightweight TOML-based format for describing a directory tree structure and its contents. Nestle-Text uses a simple and intuitive syntax that is easy to read and write, making it useful for describing and editing small projects with file structures that are complex or in flux."
readme = "README.md"
dependencies = ["binaryornot", "requests", "toml"]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
nestle = "nestle_text.nestle:main"
unnestle = "nestle_text.unnestle:main"

[project.urls]
"Source" = "https://github.com/zagaran/nestle-text"
"""

["README.md"]
source = "./README.md"
